### ISSUE TITLE
Heroku server down

### ISSUE THREAD

**Issue by KyleAMathews** [RisingStack/graffiti-example#3]
fyi

**Comment by hekike** [comment]
@KyleAMathews thanks but it's not down just running on free Heroku plan and sleeping, takes a minutes to wake up :)

**Comment by KyleAMathews** [comment]
Wakie wakie widdle Heroku! :)

Actually... the main "bug" here was my understanding. I did actually get JSON to return before, I just assumed I'd be going to a GraphiQL instance with a pre-created query.

**Comment by hekike** [comment]
sometimes happens :)
